### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by Silex**
Same as for quasascale-backend, don't merge yet, open for discussion.

I noticed I could not use `node:latest`, it needed `node:20` instead of `node:23`.

Otherwise it builds fine and should be good to use.

### CODE REVIEW

**Comment by reyzzz** [comment]
server {
    listen      80;
    server_name your.url.com;
    charset utf-8;
    root    /var/www/yoursite;
    index   index.html;

    gzip on;
    gzip_vary on;
    gzip_comp_level 5;
    #gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types *;
    gzip_disable "MSIE [1-6]\.";


    #Always serve index.html for any request
    location / {
        root /var/www/yoursite;
        try_files $uri $uri/ /index.html;
    }
    error_log  /var/log/nginx/yoursite-error.log;
    access_log /var/log/nginx/yoursite-access.log;
}

**Comment by Silex** [comment]
Same message as for other quasascale-backend issue, but let's solve image logic there and then we apply the same here.

**Comment by Silex** [comment]
Ok you can merge this.

**Comment by Silex** [comment]
Ok I imported the same changes as for the backend PR.

Merge the backend PR first and if it works like expected we can merge this one.

Then I'll create an example docker-compose.yml

**Pull request merged**
